### PR TITLE
Adding basic circleCI testing

### PR DESCRIPTION
**Pull request by mkohn**
This is going to break but a new branch from @onwsk8r should be coming down the line this week to fix it.

### CODE REVIEW

**Review by szolla — APPROVED** [review]
Looks good.

**Review by robloxrob — APPROVED** [review]
LGTM

I see the linting checks are failing, so we should fix those

**Comment by mkohn** [comment]
Yep brian has all the fixes coming soon.

**Comment by robloxrob** [comment]
Merge when your are ready here or fix the CI issues and then let me review again

**Comment by onwsk8r** [comment]
Should be cool to merge, see #10 for a working CircleCI build. Once this PR is merged @mkohn feel free to LGTM that one, which is built off this branch.

**Pull request merged**
